### ISSUE TITLE
Youtube Account Suspended.

### ISSUE THREAD

**Issue by SKumarMN** [KnowledgeCenterYoutube/LeetCode#4]
Hi,

I have been following your videos and its is very helpful. All of a sudden today, I see your youtube account is suspended. Can you please do the needful to revoke the suspension so that your videos would be very helpful for us. Since I didnt know to reach you, am raising a ticket here

**Comment by KnowledgeCenterYoutube** [comment]
My Youtube account was compromised by some Ripple Foundation group of hackers and used to stream illegal contents related to bitcoin mining, and deleted. It has now been reinstated with the help of Google Youtube Support. 
Thanks to the Youtube Support team for such a quick resolution.
Marking this issue as closed.

**Comment by SKumarMN** [comment]
Happy to see your channel back :)
